using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Sdl.Web.Tridion.Templates")]
[assembly: AssemblyDescription("SDL DXA CM Templates")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("SDL Group")]
[assembly: AssemblyProduct("SDL Digital Experience Accelerator")]
[assembly: AssemblyCopyright("Copyright © 2014-2015 SDL Group")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("c23d003e-156c-43ef-947d-9cdb6cce1b8e")]

// NOTE: Version Info is generated by the build in VersionInfo.cs
