name: Release

on:
  release:
    types: [ created ]

jobs:
  release:
    name: Release on Sonatype OSS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: chmod +x release.sh; ./release.sh
